# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.CharField(default='', max_length=150, verbose_name='个人描述'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(default=user.models.default_sign, max_length=50, verbose_name='个人描述'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
